### ISSUE TITLE
Best practice for creating a note including resource(s)

### ISSUE THREAD

**Issue by KraxelHuber** [foxmask/joplin-api#10]
What is considered to be best practice for creating a note that contains some resources, such as .png files and/or .pdf files? My thinking goes along those lines:

1. Creating a note with content (and get its ID)
2. Creating a resource and get its ID
3. Update note and include something like this to the content of the note in order to have a link to resource in note:
\!\[FILENAME\]\(:/ID\)
Repeat step 2. and 3. for all resources

It would be easier if it would be possible to assign a pre-defined ID to a resource. The process could then look like this:

1. Creating a note with content (and get its ID)
    That content would contain the following line(s):
     !\[FILENAME\]\(:/PRE-DEFINED-ID-OF-RESOURCE\)
2. Creating a resource and assign it the pre-defined ID of step 1

If the second way of attaching a resource is possible, the question is how to define a pre-defined ID? It must be made sure that the ID is unique. How to do that?

**Comment by foxmask** [comment]
Why not just ?
1. create resource and get the ID
1. create the note with the resources ID 

eg (not tested) 
```res = await joplin.create_resource(...)
    resource_id = res.json()['id']
    body = "![filename](:/{})".format(resource_id)
    res = await joplin.create_note(title="NOTE TEST", body=body,
                                   parent_id=parent_id, **kwargs)
```

**Comment by KraxelHuber** [comment]
That sounds very reasonable ;-)

And it works :-)
