### ISSUE TITLE
Can't install API

### ISSUE THREAD

**Issue by bobjones0** [foxmask/joplin-api#19]
I'm trying to install joplin-api in PyCharm which fails. I've tried in a powershell and get a similar error.

Here is the error I receive with some redaction:

ERROR: Command errored out with exit status 1: 'C:\Users\......\venv\Scripts\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\......\\AppData\\Local\\Temp\\pycharm-packaging\\immutables\[setup.py](http://setup.py)'"'"'; __file__='"'"'C:\\Users\\......\\AppData\\Local\\Temp\\pycharm-packaging\\immutables\[setup.py](http://setup.py)'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\......\AppData\Local\Temp\pip-record-weg7w0b_\install-record.txt' --single-version-externally-managed --compile --install-headers 'C:\Users\......\venv\include\site\python3.6\immutables' Check the logs for full command output.

With powershell:

    ERROR: Command errored out with exit status 1:
     command: 'c:\program files (x86)\python36-32\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\......\\AppData\\Local\\Temp\\pip-install-2sd_3d1w\\immutables\\setup.py'"'"'; __file__='"'"'C:\\Users\\......\\AppData\\Local\\Temp\\pip-install-2sd_3d1w\\immutables\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\......\AppData\Local\Temp\pip-record-e4132lzh\install-record.txt' --single-version-externally-managed --user --prefix= --compile --install-headers 'C:\Users\......\AppData\Roaming\Python\Python36\Include\immutables'
         cwd: C:\Users\......\AppData\Local\Temp\pip-install-2sd_3d1w\immutables\
    Complete output (24 lines):
    running install
    running build
    running build_py
    creating build
    creating build\lib.win32-3.6
    creating build\lib.win32-3.6\immutables
    copying immutables\map.py -> build\lib.win32-3.6\immutables
    copying immutables\_testutils.py -> build\lib.win32-3.6\immutables
    copying immutables\_version.py -> build\lib.win32-3.6\immutables
    copying immutables\__init__.py -> build\lib.win32-3.6\immutables
    running egg_info
    writing immutables.egg-info\PKG-INFO
    writing dependency_links to immutables.egg-info\dependency_links.txt
    writing top-level names to immutables.egg-info\top_level.txt
    reading manifest file 'immutables.egg-info\SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    writing manifest file 'immutables.egg-info\SOURCES.txt'
    copying immutables\_map.c -> build\lib.win32-3.6\immutables
    copying immutables\_map.h -> build\lib.win32-3.6\immutables
    copying immutables\_map.pyi -> build\lib.win32-3.6\immutables
    copying immutables\py.typed -> build\lib.win32-3.6\immutables
    running build_ext
    building 'immutables._map' extension
    error: Microsoft Visual C++ 14.0 is required. Get it with "Build Tools for Visual Studio": https://visualstudio.microsoft.com/downloads/
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'c:\program files (x86)\python36-32\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\......\\AppData\\Local\\Temp\\pip-install-2sd_3d1w\\immutables\\setup.py'"'"'; __file__='"'"'C:\\Users\\......\\AppData\\Local\\Temp\\pip-install-2sd_3d1w\\immutables\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\......\AppData\Local\Temp\pip-record-e4132lzh\install-record.txt' --single-version-externally-managed --user --prefix= --compile --install-headers 'C:\Users\......\AppData\Roaming\Python\Python36\Include\immutables' Check the logs for full command output.

Thanks

**Comment by foxmask** [comment]
do you open a pycharm terminal and enter pup install joplin-api ?

**Comment by bobjones0** [comment]
> do you open a pycharm terminal and enter pup install joplin-api ?

Yes, I receive the same error this way.

**Comment by bobjones0** [comment]
I solved this problems by installing Microsoft Visual C++ 14.0.
