### ISSUE TITLE
Note updates erased for unspecified note data

### ISSUE THREAD

**Issue by dpetz** [foxmask/joplin-api#21]
In [update_note](https://github.com/foxmask/joplin-api/blob/b6c6f3ab75c88addab18bb475c21d937bc10efcd/joplin_api/core.py#L209) properties not specified in `kwargs` are set to default values and then send to the server.
This should be documented or changed to the saver behavior to not send fields that were not specified by the called.

This is particular troublesome for the `tags`field. Tags are not returned by `get_note` so when you get a note and then update (even w/o any change) tags will be lost. To avoid user needs to be aware + do extra round trips to get tags before updating.

If PRs from new contributors are desired I can provide the fix myself.

**Comment by foxmask** [comment]
yes, feel to provide a PR.
thanks.
and that will count for the Hacktoberfest if you are interested in that event.

**Comment by foxmask** [comment]
I checked, to get tags with note it's 
```
get_notes_tags
```
