### ISSUE TITLE
How to set note's creation date

### ISSUE THREAD

**Issue by KraxelHuber** [foxmask/joplin-api#9]
Hi,

When creating a new note, I would like to pass a creation date. Can you please provide a coding example?

**Comment by foxmask** [comment]
it's not possible, joplin set it all alone when a note is created

**Comment by laurent22** [comment]
Note that while the updated_time and created_time property are set automatically, the user_updated_time and user_created_time can be set by the user. This is usually this date you see in the UI.

**Comment by foxmask** [comment]
if you'd like to set that property : 
you can use it like this.
and set the user_time_created with the current time


```
import asyncio
import time;
from joplin_api import JoplinApi
joplin = JoplinApi(token='my token')

async def new_note(get_token):
    # 1 - create a folder
    res = await joplin.create_folder(folder='MY FOLDER')
    data = res.json()
    parent_id = data['id']
    # 2 - create a note with tag
    body = '# title 1\n ## subtitle \n ```python\npython --version\n```'
    assert type(body) is str
    ts = time.time()
    kwargs = {'tags': 'tag1, tag2', 'user_created_time': ts }
    await joplin.create_note(title="MY NOTE", body=body,
                             parent_id=parent_id, **kwargs)

loop = asyncio.get_event_loop()
try:
    loop.run_until_complete(new_note())
finally:
    loop.close()
```

I didnt test it.
You can use any property of this page https://joplinapp.org/api/ you want and put them in the `**kwargs` that will be given to the create_note method.

Hope this will help.

**Comment by KraxelHuber** [comment]
I am facing some issues when trying to implement the property `user_created_time`. When creating a note, this propertiy seems to be ignored.

I changed one of your unit tests, namely `test_create_note` in file `test_folder.py` (see below). This test is failing.

```
async def test_create_note(get_token):
    joplin = JoplinApi(token=get_token)
    # 1 - create a folder
    res = await joplin.create_folder(folder='MY FOLDER3')
    data = res.json()
    parent_id = data['id']
    assert type(parent_id) is str
    # 2 - create a note with tag
    body = '# title 1\n ## subtitle \n ```python\npython --version\n```'
    assert type(body) is str
    kwargs = {'tags': 'tag1, tag2', 'id': '00a87474082744c1a8515da6aa5792d2',
              'user_created_time': 1000000}
    assert 'id' in kwargs
    assert re.match('[a-z0-9]{32}', kwargs['id'])
    res = await joplin.create_note(title="NOTE TEST", body=body,
                                   parent_id=parent_id, **kwargs)
    assert res.status_code == 200
    note_id = res.json()['id']
    note_user_created_time = res.json()['user_created_time']
    assert note_user_created_time == 1000000  # fails here: note_user_created_time is equal to the current time
    """
    # 3 - update a note with tag
    body = '# title 1\n ## subtitle \n ```python\npython --version\n```'
    assert type(body) is str
    # BUG : joplin does not update TAG yet
    # @TOFIX once fixed by Joplin
    kwargs = {'tags': 'tag1, tag2, tag11'}
    res = await joplin.update_note(note_id=note_id,
                                   body=body,
                                   title="NOTE TEST",
                                   parent_id=parent_id,
                                   **kwargs)
    assert res.status_code == 200
    """
    # drop the testing data
    # 4 - get the tag of that note
    tags_to_delete = await joplin.get_notes_tags(note_id)
    # 5 - delete the tags
    for line in tags_to_delete.json():
        await joplin.delete_tags_notes(line['id'], note_id)

    # delete note
    await joplin.delete_note(note_id)
    # delete folder
    await joplin.delete_folder(parent_id)
```

**Comment by foxmask** [comment]
because it's not a valid date.

**Comment by foxmask** [comment]
i got it

**Comment by foxmask** [comment]
I thought the kwargs was offered to the payload but in fact no 
the "merge" ` {**data , **kwargs}` fixes that

**Comment by KraxelHuber** [comment]
Hmm, the test is now passing. However, there's still something wrong, in my view.

Try to set a breakpoint at line 80 of the particular test. Debug the code and switch to the Joplin App and take a look at the note's creation date. On my end, it's 1970-01-18 22:22.

https://github.com/foxmask/joplin-api/blob/32a6f31c8c417efa5490ec1a7081ac968f6196b6/tests/test_folder.py#L80

![image](https://user-images.githubusercontent.com/29901736/74102582-1ed00f80-4b45-11ea-9a57-1ad3c0eddeb7.png)

**Comment by KraxelHuber** [comment]
Is it possible that Joplin interpretes the timestamp differently from what Python does? If I translate the timestamp within the unit test, I do get the following result:

```
timestamp = 1545730073
time.strftime('%Y-%m-%d %H:%M', time.localtime(timestamp))
'2018-12-25 10:27'
```

**Comment by foxmask** [comment]
Joplin store it as a pure integer as I could see in an issue about that.
so you should use a timestamp and nothing else

**Comment by foxmask** [comment]
you can checkout that assertion here https://joplinapp.org/api/

**Comment by KraxelHuber** [comment]
I am just wondering what `int` equals a specific date?
When creating a note without specifiying an int-datenumber, Joplin sends back a 13 digit `int`, such as `1581273971523`. If I transfer this to a human readable date (btw. am I doing this correctly?), I get:

```
time.strftime('%Y-%m-%d %H:%M', time.localtime(1581273971523))
'52078-07-30 02:52'
```

`1581273971523` is read from `res['created_time']`.

On the other hand, I provided a 10 digit `int`, which amounts to the year 1970. As a result, I think that I am simply providing the wrong datenum `int`. What would be the correct datenum `int` for, let's say, 2020-02-04? What's the way to compute it?

**Comment by foxmask** [comment]
it seems to be stored in miliseconds
>>> time.strftime('%Y-%m-%d %H:%M', time.localtime(1581273971523/1000))
'2020-02-09 19:46'
>>>

**Comment by foxmask** [comment]
API doc says 
> About the property types🔗
>    Text is UTF-8.
>    All date/time are Unix timestamps in milliseconds.
>    Booleans are integer values 0 or 1.

**Comment by KraxelHuber** [comment]
Yep, miliseconds are correct. Multiplying my 10 digit `int` generates the correct date.
Great! Thanks a lot!
